version: '3.8'

services:
  # Node.js应用服务
  fans-fee-app:
    build: .
    container_name: fans-fee-app
    environment:
      - NODE_ENV=production
      - PORT=34145
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fans-fee-network
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    # 安全设置
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:34145/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx反向代理服务
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: fans-fee-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书目录
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fans-fee-network
    depends_on:
      fans-fee-app:
        condition: service_healthy
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # 安全设置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m
      - /tmp:noexec,nosuid,size=10m
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai

  # 监控服务 (可选)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: fans-fee-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
      - TZ=Asia/Shanghai
    command: --interval 3600 --cleanup fans-fee-app fans-fee-nginx
    networks:
      - fans-fee-network
    profiles:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  fans-fee-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.name: fans-fee-br0
      com.docker.network.driver.mtu: 1500

# 数据卷定义
volumes:
  nginx-logs:
    driver: local
  app-logs:
    driver: local