version: '3.8'

services:
  # Node.js应用服务
  fans-fee-app:
    build: .
    container_name: fans-fee-app
    ports:
      - "34145:34145"
    environment:
      - NODE_ENV=production
      - PORT=34145
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fans-fee-network
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    # 安全设置
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:34145/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fans-fee-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.name: fans-fee-br0
      com.docker.network.driver.mtu: 1500

# 数据卷定义
volumes:
  app-logs:
    driver: local